[
    {
      "id": 47,
      "name": "Robert \"Bob\" Belcher, Jr.",
      "image": "https://bobsburgers-api.herokuapp.com/images/characters/47.jpg",
      "gender": "Male",
      "age": "46",
      "occupation": "Chef/owner and operator of Bob's Burgers",
      "relatives": [
        "https://bobsburgers-api.herokuapp.com/characters/275",
        "https://bobsburgers-api.herokuapp.com/characters/170",
        "https://bobsburgers-api.herokuapp.com/characters/483",
        "https://bobsburgers-api.herokuapp.com/characters/280",
        "https://bobsburgers-api.herokuapp.com/characters/180",
        "https://bobsburgers-api.herokuapp.com/characters/5",
        "https://bobsburgers-api.herokuapp.com/characters/169",
        "https://bobsburgers-api.herokuapp.com/characters/45",
        "Mrs. Belcher",
        "Ernest Lombard",
        "https://bobsburgers-api.herokuapp.com/characters/500",
        "Burt",
        "Marie"
      ],
      "firstEpisode": "\"Human Flesh\"",
      "voicedBy": "H. Jon Benjamin",
      "url": "https://bobsburgers-api.herokuapp.com/characters/47"
    },
    {
      "id": 48,
      "name": "Boo Boo",
      "image": "https://bobsburgers-api.herokuapp.com/images/characters/48.jpg",
      "gender": "Male",
      "hairColor": "Blonde",
      "occupation": "Member of Boyz4Now",
      "firstEpisode": "\"Boyz 4 Now\"",
      "voicedBy": "Max Greenfield",
      "url": "https://bobsburgers-api.herokuapp.com/characters/48"
    },
    {
      "id": 168,
      "name": "Gene Belcher",
      "image": "https://bobsburgers-api.herokuapp.com/images/characters/168.jpg",
      "gender": "Male",
      "age": "11",
      "hairColor": "Black",
      "occupation": "Student",
      "relatives": [
        "https://bobsburgers-api.herokuapp.com/characters/275",
        "https://bobsburgers-api.herokuapp.com/characters/47",
        "https://bobsburgers-api.herokuapp.com/characters/483",
        "https://bobsburgers-api.herokuapp.com/characters/280",
        "https://bobsburgers-api.herokuapp.com/characters/180",
        "https://bobsburgers-api.herokuapp.com/characters/5",
        "https://bobsburgers-api.herokuapp.com/characters/169",
        "https://bobsburgers-api.herokuapp.com/characters/45",
        "Mrs. Belcher",
        "Ernest Lombard",
        "Burt",
        "https://bobsburgers-api.herokuapp.com/characters/500"
      ],
      "firstEpisode": "\"Human Flesh\"",
      "voicedBy": "Eugene Mirman",
      "url": "https://bobsburgers-api.herokuapp.com/characters/168"
    },
    {
      "id": 261,
      "name": "Kurt Enerny",
      "image": "https://bobsburgers-api.herokuapp.com/images/characters/261.jpg",
      "gender": "Male",
      "hairColor": "Blonde",
      "occupation": "Pilot",
      "relatives": [
        "https://bobsburgers-api.herokuapp.com/characters/271"
      ],
      "firstEpisode": "\"Seaplane!\"",
      "voicedBy": "Will Forte",
      "url": "https://bobsburgers-api.herokuapp.com/characters/261"
    },
    {
      "id": 272,
      "name": "Linda Belcher",
      "image": "https://bobsburgers-api.herokuapp.com/images/characters/272.jpg",
      "gender": "Female",
      "age": "44",
      "hairColor": "Black",
      "occupation": "Cook at Bob's Burgers",
      "relatives": [
        "https://bobsburgers-api.herokuapp.com/characters/5",
        "https://bobsburgers-api.herokuapp.com/characters/180",
        "https://bobsburgers-api.herokuapp.com/characters/169",
        "https://bobsburgers-api.herokuapp.com/characters/47",
        "https://bobsburgers-api.herokuapp.com/characters/483",
        "https://bobsburgers-api.herokuapp.com/characters/170",
        "https://bobsburgers-api.herokuapp.com/characters/280",
        "https://bobsburgers-api.herokuapp.com/characters/45",
        "Mrs. Belcher",
        "Ernest Lombard",
        "https://bobsburgers-api.herokuapp.com/characters/500",
        "Burt",
        "Marie"
      ],
      "firstEpisode": "\"Human Flesh\"",
      "voicedBy": "John Roberts",
      "url": "https://bobsburgers-api.herokuapp.com/characters/272"
    },
    {
      "id": 277,
      "name": "Louise Belcher",
      "image": "https://bobsburgers-api.herokuapp.com/images/characters/277.jpg",
      "gender": "Female",
      "age": "9",
      "hairColor": "Black",
      "occupation": "Works at the family restaurant",
      "relatives": [
        "https://bobsburgers-api.herokuapp.com/characters/275",
        "https://bobsburgers-api.herokuapp.com/characters/47",
        "https://bobsburgers-api.herokuapp.com/characters/483",
        "https://bobsburgers-api.herokuapp.com/characters/170",
        "https://bobsburgers-api.herokuapp.com/characters/180",
        "https://bobsburgers-api.herokuapp.com/characters/5",
        "https://bobsburgers-api.herokuapp.com/characters/169",
        "https://bobsburgers-api.herokuapp.com/characters/45",
        "Ernest Lombard",
        "Mrs. Belcher",
        "Burt",
        "https://bobsburgers-api.herokuapp.com/characters/500"
      ],
      "firstEpisode": "\"\"Human Flesh\"\"",
      "voicedBy": "Kristen Schaal",
      "url": "https://bobsburgers-api.herokuapp.com/characters/277"
    },
    {
      "id": 293,
      "name": "Marshmallow",
      "image": "https://bobsburgers-api.herokuapp.com/images/characters/293.jpg",
      "gender": "Female",
      "age": "23",
      "hairColor": "Black",
      "occupation": "Sex Worker",
      "firstEpisode": "\"Sheesh! Cab, Bob?\"",
      "voicedBy": "David Herman (formerly), ",
      "url": "https://bobsburgers-api.herokuapp.com/characters/293"
    },
    {
      "id": 351,
      "name": "Natalie \"Nat\" Kinkle",
      "image": "https://bobsburgers-api.herokuapp.com/images/characters/351.jpg",
      "gender": "Female",
      "age": "20s-30s",
      "hairColor": "Brown",
      "occupation": "Limousine Driver",
      "firstEpisode": "\"V for Valentine-detta\"",
      "voicedBy": "Jillian Bell",
      "url": "https://bobsburgers-api.herokuapp.com/characters/351"
    },
    {
      "id": 386,
      "name": "Peter Pescadero",
      "image": "https://bobsburgers-api.herokuapp.com/images/characters/386.jpg",
      "gender": "Male",
      "age": "11",
      "hairColor": "Red",
      "occupation": "Student at Wagstaff School",
      "firstEpisode": "\"Spaghetti Western and Meatballs\"",
      "voicedBy": "H. Jon Benjamin",
      "url": "https://bobsburgers-api.herokuapp.com/characters/386"
    },
    {
      "id": 447,
      "name": "Sofa Queen",
      "image": "https://bobsburgers-api.herokuapp.com/images/characters/447.jpg",
      "gender": "Female",
      "hairColor": "Black",
      "occupation": "Spokesperson/owner of Sofa Queen",
      "relatives": [
        "https://bobsburgers-api.herokuapp.com/characters/456"
      ],
      "firstEpisode": "\"Sacred Couch\"",
      "voicedBy": "Wanda Sykes",
      "url": "https://bobsburgers-api.herokuapp.com/characters/447"
    },
    {
      "id": 473,
      "name": "Tina Ruth Belcher",
      "image": "https://bobsburgers-api.herokuapp.com/images/characters/473.jpg",
      "gender": "Female",
      "age": "13",
      "hairColor": "Black",
      "occupation": "Grill Cook at Bob's Burgers",
      "relatives": [
        "https://bobsburgers-api.herokuapp.com/characters/47",
        "https://bobsburgers-api.herokuapp.com/characters/275",
        "https://bobsburgers-api.herokuapp.com/characters/170",
        "https://bobsburgers-api.herokuapp.com/characters/280",
        "https://bobsburgers-api.herokuapp.com/characters/5",
        "https://bobsburgers-api.herokuapp.com/characters/180",
        "https://bobsburgers-api.herokuapp.com/characters/169",
        "https://bobsburgers-api.herokuapp.com/characters/45",
        "Mrs. Belcher",
        "Ernest Lombard",
        "Burt",
        "https://bobsburgers-api.herokuapp.com/characters/500"
      ],
      "firstEpisode": "\"Human Flesh\"",
      "voicedBy": "Dan Mintz",
      "url": "https://bobsburgers-api.herokuapp.com/characters/473"
    },
    {
      "id": 496,
      "name": "Yuki Kojima",
      "image": "https://bobsburgers-api.herokuapp.com/images/characters/496.jpg",
      "gender": "Female",
      "age": "40",
      "hairColor": "Black",
      "occupation": "Former movie actress, Accountant at Deduction Junction",
      "relatives": [
        "https://bobsburgers-api.herokuapp.com/characters/442",
        "Unnamed mother",
        "Unnamed son"
      ],
      "firstEpisode": "\"Hawk & Chick\"",
      "voicedBy": "Suzy Nakamura",
      "url": "https://bobsburgers-api.herokuapp.com/characters/496"
    }
  ]